language: minimal

services:
  - docker

script:
  - docker build -t ulise/hetida-designer-web:0.1.D${TRAVIS_BUILD_NUMBER} -f Dockerfile-frontend .
  - docker build -t ulise/hetida-designer-backend:0.1.D${TRAVIS_BUILD_NUMBER} -f Dockerfile-backend .
  - docker build -t ulise/hetida-designer-runtime:0.1.D${TRAVIS_BUILD_NUMBER} --target prod -f Dockerfile-runtime .
